ydlidar_ros2_driver_node:
  ros__parameters:
    port: /dev/ttyLiDAR
    frame_id: base_scan
    ignore_array: ""
    baudrate: 230400
    lidar_type: 1
    device_type: 0
    sample_rate: 5
    abnormal_check_count: 4
    resolution_fixed: true
    reversion: false
    inverted: true
    auto_reconnect: true
    isSingleChannel: false
    intensity: true
    support_motor_dtr: false
    angle_max: 180.0
    angle_min: -180.0
    range_max: 16.0
    range_min: 0.1
    frequency: 10.0
    invalid_range_is_inf: false
